name: GAN_SHL
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=2.108
  - blas-devel=3.9.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cloudpickle=1.6.0
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - decorator=4.4.2
  - freetype=2.10.4
  - future=0.18.2
  - hyperopt=0.2.5
  - icu=58.2
  - imbalanced-learn=0.8.0
  - intel-openmp=2020.3
  - joblib=0.17.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.41.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - msys2-conda-epoch=20160418
  - networkx=2.5
  - ninja=1.10.2
  - numpy=1.20.1
  - olefile=0.46
  - openssl=1.1.1j
  - pandas=1.2.3
  - pillow=8.1.2
  - pip=21.0.1
  - pymongo=3.11.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.8.0
  - pytz=2020.1
  - qt=5.9.7
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - seaborn=0.11.0
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.2
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
