name: GAN_SHL
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cloudpickle=1.6.0
  - cudatoolkit=11.1.1
  - future=0.18.2
  - hyperopt=0.2.5
  - imbalanced-learn=0.8.0
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - numpy=1.20.1
  - pandas=1.2.3
  - pip=21.0.1
  - pyqt=5.9.2
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.8.0
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - seaborn=0.11.0
